### ISSUE TITLE
5.0.0 no longer supports limiting fetchDepth

### ISSUE THREAD

**Issue by marcphilipp** [ajoberstar/gradle-git-publish#114]
Instead, it now fails because it cannot find the parent commit (which wasn't fetched):
```
error: Could not read 469570e1d0d6a04ba9739272246ae85691b2a160	
error: Could not read 469570e1d0d6a04ba9739272246ae85691b2a160	
fatal: Failed to traverse parents of commit 97f36a4b958c5315b6577f6c71bde9d148576767	
error: remote did not send all necessary objects
```

https://ge.junit.org/s/77op2apoehs7w/console-log/task/:gitPublishReset?anchor=4&page=1

**Comment by marcphilipp** [comment]
I tried setting `fetchDepth` to `2` but that failed as well:
https://ge.junit.org/s/4yu7m4cnv5zei/console-log/task/:gitPublishReset?anchor=4&page=1

**Comment by ajoberstar** [comment]
I'll look into this later today.

**Comment by ajoberstar** [comment]
Seems like the issue is the new use of `.git/objects/info/alternates` to save on fetch time is not compatible with shallow clones. Added logic to skip use of alternates if fetch depth is set or if the reference repo is a shallow clone.

Will get a 5.1.0 out. I tested this against your project, so I'm pretty sure it should do the trick.
