### ISSUE TITLE
Injecting credentials no longer seems to work with 5.0.0

### ISSUE THREAD

**Issue by marcphilipp** [ajoberstar/gradle-git-publish#115]
After removing `fetchDepth` to work around #114, I'm now running into the next problem:
```
:gitPublishPush FAILED	
fatal: could not read Username for 'https://github.com/': No such device or address
```
https://ge.junit.org/s/oouojjedzzoja/console-log/task/:gitPublishPush?anchor=1&page=1

I'm injecting credentials by setting the `GRGIT_USER` env var. Has anything changed in this regard?

**Comment by ajoberstar** [comment]
Yes, in switching to the Git cli all of the grgit specific authentication options don't work anymore.

Will look into this more later today.

**Comment by marcphilipp** [comment]
That makes sense! It's still documented in the repo's README, though. What's the new recommendation for configuring credentials?

**Comment by ajoberstar** [comment]
I'll remove that mention from the README. Since it all happened implicitly via grgit before, it slipped my mind to come up with an alternative in the cli impl.

Guessing I'll need to add a `credentials {}` block into the publication so that people can choose how to retrieve their creds as best suits them.

**Comment by ajoberstar** [comment]
Added `username` and `password` properties to `GitPublication`. If they're both set, they'll get passed to the relevant commands via a credential helper.

Will be in 5.1.0.
