### ISSUE TITLE
Credential migration from gh-pages plugin

### ISSUE THREAD

**Issue by nedtwigg** [ajoberstar/gradle-git-publish#33]
If we were publishing like this:

```gradle
githubPages {
    repoUri = 'https://github.com/org/repo'
    credentials {
        username = "$gh_token"
        password = ''
    }
}
```

How should we handle this in gradle-git-publish?

**Comment by ajoberstar** [comment]
Currently the approach would be to leverage either the `GRGIT_USER` environment variable or the `org.ajoberstar.grgit.auth.username` system property.

**Comment by nedtwigg** [comment]
Want a PR that puts this into the gh-publish migration instructions?

**Comment by ajoberstar** [comment]
That would be great!

**Comment by nedtwigg** [comment]
BTW, I tried setting the GRGIT_USER variable, but I still get a Swing login panel.  Any hints?

**Comment by nedtwigg** [comment]
My bad, I figured it out.  My creds were just stale.  Might be better to get an "AUTH failed" error than a Swing dialog.

**Comment by ajoberstar** [comment]
That behavior is due to some peculiarities of JGit's authentication. If you have bad creds it wants to have an option to prompt the user, which I have configured to (by default) use a dialog for any input. That can be disabled (see the allow interactive = false [option](http://ajoberstar.org/grgit/grgit-authentication.html)). You'd get an exception in that case.

Besides some lingering issues with host keys, I'd probably prefer to default that to disabled. maybe for 3.0.
