### ISSUE TITLE
Error getting GitPublishCommit.repoDirectory

### ISSUE THREAD

**Issue by grv87** [ajoberstar/gradle-git-publish#60]
I have [custom diagnostic task that creates report about inputs and outputs of each task](https://github.com/FIDATA/gradle-base-plugins/blob/598e63240edb24c0fffcbdb0888348f3f4da3aeb/src/main/groovy/org/fidata/gradle/tasks/InputsOutputs.groovy).

Unfortunately, I can't use it with this plugin:
```
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
        at org.ajoberstar.gradle.git.publish.tasks.GitPublishCommit.getRepoDirectory(GitPublishCommit.java:40)
        at org.ajoberstar.gradle.git.publish.tasks.GitPublishCommit_Decorated.getRepoDirectory(Unknown Source)
```

I see that the problem is that grgit value is set during GitPublishReset task execution only:
https://github.com/ajoberstar/gradle-git-publish/blob/b0e47c8d20d240ad118eca4fab31d5afba71e4fc/src/main/java/org/ajoberstar/gradle/git/publish/tasks/GitPublishReset.java#L81-L82

Maybe I don't understand something, but why it is not set just after property creation? It could still be lazy (maybe with additional provider).

**Comment by ajoberstar** [comment]
You can see the background in [this commit](https://github.com/ajoberstar/gradle-git-publish/commit/f5add2e6b070056827ebd93666a277a937f47242). There may be some other ways to do it, but I'd like to keep up no providers and also avoid the logic happening multiple times.

**Comment by grv87** [comment]
Hit this again in tests trying to disable all tasks via `tasks*.enabled = false`.

I see there is a logic error in current implementation.
`GitPublishReset.grgit` is a `Property` but its value is completely ignored and is overridden in `reset`.
What's the reason then to store it as a `Property` and to expose it publicly?

**Comment by ajoberstar** [comment]
Does making it a `Provider` instead of a Property (from a public perspective) improve the situation for you?

I basically need three things:

- To only try to clone/open the repo once
- To clone/open it only if you intend to use it (i.e. running the `gitPublishReset` task)
- To share that repo instance across all tasks

In the current state of providers, setting it at task runtime is the cleanest way for me to handle this, though the current option does have the side effect that the Property's value would be ignored if already set.

Thinking about your input/output report use case, you may want to support Property/Providers that aren't set anyway. It doesn't seem invalid for a property to have no value.

**Comment by ysb33r** [comment]
I ran into the same thing today. I put this seemingly innocent code in the the build script and it causes the issue.

```groovy
['Reset','Push','Commit'].each {
    tasks.named("gitPublish${it}") {
        enabled = pushDocs
    }
}
```

Take the code out and it works.

Same thing happens with 

```groovy
['Reset','Push','Commit'].each {
    tasks.named("gitPublish${it}") {
        onlyIf {pushDocs}
    }
}
```

My only workaround is not to call `gitPublishPush` directly, but rather have a lifecycle publish task which will only depend on the `gitPublish*` tasks if my variable `pushDocs` is set.

@ajoberstar You might be better off if the project extension creates the GrGit object rather that the task. You can still have it created on demand. It is also better in my experience to use `Provider` rather than `Property`.
