### ISSUE TITLE
Use sync task instead of copy?

### ISSUE THREAD

**Issue by netvl** [ajoberstar/gradle-git-publish#69]
Currently the plugin uses the standard `Copy` task to copy files into the repository. However, if one always publishes documentation to a single directory, e.g. it is a directory with snapshot documentation generated upon each commit, then it leaves a potential for garbage files to accumulate in the repository (for example, a class has been removed from the library, but its javadoc file is still present in the gh-pages tree).

However, Gradle does have a task which synchronizes contents of directories, removing files which are no longer there, and it is the standard `Sync` task. Maybe `gitPublishCopy` should use `Sync` instead of `Copy`, or at least provide it as an option?

**Comment by ajoberstar** [comment]
The `gitPublishReset` task will delete all files in the repo (except those kept by the `preserve` option in the `gitPublish` extension). The `gitPublishCopy` is then a simple copy, because files deleted from the source were already removed by the reset task. We could probably use `Sync` but it would end up functioning the same.

See the README for the options on the extension.

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
