### ISSUE TITLE
Unnecessarily opening repo

### ISSUE THREAD

**Issue by shevek** [ajoberstar/gradle-git-publish#70]
When I ran gradle -i with a build which uses gitPublish, I see the following log message at the end of the build:

```
Closing Git publish repo: /path/to/repo
```

This is despite **NOT** asking for the execution of any task which touched the gitPublish task or repo. Is this a potential performance issue on large builds?

**Comment by ajoberstar** [comment]
I think this is a symptom of using [grgit](https://github.com/ajoberstar/grgit/blob/b2c1fec826db19c1b05ca5665d5cc2624b2224ca/grgit-gradle/src/main/groovy/org/ajoberstar/grgit/gradle/GrgitPlugin.groovy#L17) rather than gradle-git-publish itself. I think it would require a change there to delay opening a git repo until you meant to use one.
